In [27]:
%pip install pandas
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [28]:
doctor=pd.read_csv("/workspaces/CareFlow-Clinical-Pathway-Process-Mining/doctors.csv")

In [29]:
doctor.head()

,doctor_id,doctor_name,specialization,department,doctor_type,experience_years,consultation_fee,doctor_shift,max_patients_per_day
0,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0
1,DOC511,Dr. Venkatesh Kulkarni,ENT Specialist,ENT,OPD Only,5,800,Morning,50
2,DOC512,Dr. Mohammed Arora,Neurologist,Neurology,Both,6,1500,Morning,45
3,DOC513,Dr. Shweta Mittal,Pulmonologist,Pulmonology,IPD Only,33,1000,Morning,0
4,DOC514,Dr. Parminder Reddy,Orthopedic Surgeon,Orthopedics,Both,17,1000,Evening,42

In [30]:
patient=pd.read_csv("/workspaces/CareFlow-Clinical-Pathway-Process-Mining/patients.csv")

In [31]:
patient.head()

,patient_id,patient_category,patient_type,visit_type,gender,age,blood_group,area,disease,severity_level,...,admission_date,discharge_date,doctor_id,treatment_cost,payment_method,insurance,patient_status,opd_waiting_time_min,room_allocation_time_min,patient_rating
0,PAT320001,Appointment,OPD,New Patient,Male,32,A+,Sector 15,Fever,Moderate,...,2026-06-22,2026-06-22,DOC550,2003,Debit Card,No,Recovered,25,0,5.0
1,PAT320002,Walk-in,OPD,New Patient,Female,12,AB-,Sector 15,Malaria,Moderate,...,2026-06-25,2026-06-25,DOC541,4318,Credit Card,No,Recovered,66,0,2.0
2,PAT320003,Appointment,OPD,New Patient,Male,1,O+,Sector 21,Child Asthma,Moderate,...,2026-06-08,2026-06-08,DOC538,2775,Debit Card,No,Recovered,12,0,4.0
3,PAT320004,Appointment,OPD,New Patient,Male,82,A+,DLF Phase 2,Stroke,Severe,...,2026-06-22,2026-06-22,DOC512,3774,UPI,No,Recovered,20,0,4.0
4,PAT320005,Emergency,IPD,New Patient,Male,19,B+,Sector 21,Road Accident,Severe,...,2026-06-15,NaN,DOC521,59018,Credit Card,No,Recovered,0,21,5.0

In [32]:
hospital=pd.merge(doctor, patient, on="doctor_id")

In [33]:
hospital.head()

,doctor_id,doctor_name,specialization,department,doctor_type,experience_years,consultation_fee,doctor_shift,max_patients_per_day,patient_id,...,referral_source,admission_date,discharge_date,treatment_cost,payment_method,insurance,patient_status,opd_waiting_time_min,room_allocation_time_min,patient_rating
0,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320065,...,Self,2026-06-16,2026-06-16,1037,UPI,No,Recovered,56,0,4.0
1,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320226,...,Self,2026-06-16,2026-06-16,4349,UPI,No,Recovered,26,0,4.0
2,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320286,...,Doctor Referral,2026-06-10,2026-06-17,65745,Credit Card,No,Recovered,0,58,3.0
3,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320346,...,Self,2026-06-08,2026-06-08,2374,UPI,Yes,Recovered,74,0,4.0
4,DOC510,Dr. Nikhil Siddiqui,Pulmonologist,Pulmonology,IPD Only,19,1000,Morning,0,PAT320349,...,Doctor Referral,2026-06-17,2026-06-17,7509,UPI,No,Recovered,6,0,3.0

In [34]:
hospital.isnull().count()

doctor_id                   40600
doctor_name                 40600
specialization              40600
department                  40600
doctor_type                 40600
experience_years            40600
consultation_fee            40600
doctor_shift                40600
max_patients_per_day        40600
patient_id                  40600
patient_category            40600
patient_type                40600
visit_type                  40600
gender                      40600
age                         40600
blood_group                 40600
area                        40600
disease                     40600
severity_level              40600
referral_source             40600
admission_date              40600
discharge_date              40600
treatment_cost              40600
payment_method              40600
insurance                   40600
patient_status              40600
opd_waiting_time_min        40600
room_allocation_time_min    40600
patient_rating              40600
dtype: int64

In [35]:
hospital.shape

(40600, 29)

In [36]:
hospital.info()

<class 'pandas.DataFrame'>
RangeIndex: 40600 entries, 0 to 40599
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   doctor_id                 40600 non-null  str
 1   doctor_name               40600 non-null  str
 2   specialization            40600 non-null  str
 3   department                40600 non-null  str
 4   doctor_type               40600 non-null  str
 5   experience_years          40600 non-null  int64
 6   consultation_fee          40600 non-null  int64
 7   doctor_shift              40600 non-null  str
 8   max_patients_per_day      40600 non-null  int64
 9   patient_id                40600 non-null  str
 10  patient_category          40600 non-null  str
 11  patient_type              40600 non-null  str
 12  visit_type                40600 non-null  str
 13  gender                    40600 non-null  str
 14  age                       40600 non-null  int64
 15  blood_group               40316 non-null  str
 16  area                      40325 non-null  str
 17  disease                   40600 non-null  str
 18  severity_level            40600 non-null  str
 19  referral_source           40600 non-null  str
 20  admission_date            40600 non-null  str
 21  discharge_date            40109 non-null  str
 22  treatment_cost            40600 non-null  int64
 23  payment_method            40344 non-null  str
 24  insurance                 40600 non-null  str
 25  patient_status            40600 non-null  str
 26  opd_waiting_time_min      40600 non-null  int64
 27  room_allocation_time_min  40600 non-null  int64
 28  patient_rating            38552 non-null  float64
dtypes: float64(1), int64(7), str(21)
memory usage: 9.0 MB

In [37]:

columns_to_drop = [
    "area",
    "referral_source",
    "room_allocation_time_min",
    "max_patients_per_day"
]

hospital = hospital.drop(columns=columns_to_drop, errors="ignore")

In [38]:
hospital.info()

<class 'pandas.DataFrame'>
RangeIndex: 40600 entries, 0 to 40599
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   doctor_id             40600 non-null  str
 1   doctor_name           40600 non-null  str
 2   specialization        40600 non-null  str
 3   department            40600 non-null  str
 4   doctor_type           40600 non-null  str
 5   experience_years      40600 non-null  int64
 6   consultation_fee      40600 non-null  int64
 7   doctor_shift          40600 non-null  str
 8   patient_id            40600 non-null  str
 9   patient_category      40600 non-null  str
 10  patient_type          40600 non-null  str
 11  visit_type            40600 non-null  str
 12  gender                40600 non-null  str
 13  age                   40600 non-null  int64
 14  blood_group           40316 non-null  str
 15  disease               40600 non-null  str
 16  severity_level        40600 non-null  str
 17  admission_date        40600 non-null  str
 18  discharge_date        40109 non-null  str
 19  treatment_cost        40600 non-null  int64
 20  payment_method        40344 non-null  str
 21  insurance             40600 non-null  str
 22  patient_status        40600 non-null  str
 23  opd_waiting_time_min  40600 non-null  int64
 24  patient_rating        38552 non-null  float64
dtypes: float64(1), int64(5), str(19)
memory usage: 7.7 MB

In [39]:
hospital.describe()

,experience_years,consultation_fee,age,treatment_cost,opd_waiting_time_min,patient_rating
count,40600.000000,40600.000000,40600.000000,40600.000000,40600.000000,38552.000000
mean,16.794852,875.911330,44.367882,27126.134852,33.721995,3.954762
std,10.151633,359.287416,36.104947,56742.770840,29.804368,1.065019
min,2.000000,500.000000,0.000000,500.000000,0.000000,1.000000
25%,8.000000,500.000000,28.000000,2505.000000,5.000000,3.000000
50%,15.000000,800.000000,44.000000,5076.500000,27.000000,4.000000
75%,27.000000,1000.000000,60.000000,7914.000000,57.000000,5.000000
max,35.000000,1800.000000,999.000000,376977.000000,120.000000,5.000000

In [40]:
hospital.duplicated().sum()

np.int64(56)

In [41]:
hospital= hospital.drop_duplicates()

In [42]:
hospital.describe(include="all")

,doctor_id,doctor_name,specialization,department,doctor_type,experience_years,consultation_fee,doctor_shift,patient_id,patient_category,...,disease,severity_level,admission_date,discharge_date,treatment_cost,payment_method,insurance,patient_status,opd_waiting_time_min,patient_rating
count,40544,40544,40544,40544,40544,40544.000000,40544.000000,40544,40544,40544,...,40544,40544,40544,40054,40544.000000,40289,40544,40544,40544.000000,38496.000000
unique,80,79,15,15,3,NaN,NaN,3,40000,3,...,85,4,30,30,NaN,5,2,5,NaN,NaN
top,DOC583,Dr. Mohit Joshi,General Physician,General Medicine,OPD Only,NaN,NaN,Morning,PAT321024,Walk-in,...,Fever,Moderate,2026-06-13,2026-06-30,NaN,UPI,No,Recovered,NaN,NaN
freq,1136,1217,10943,10943,15108,NaN,NaN,29257,2,20312,...,2051,27883,1624,3662,NaN,12526,26184,33000,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,16.794914,875.843528,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,27040.598609,NaN,NaN,NaN,33.768326,3.954489
std,NaN,NaN,NaN,NaN,NaN,10.151065,359.084455,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,56677.538933,NaN,NaN,NaN,29.798802,1.064955
min,NaN,NaN,NaN,NaN,NaN,2.000000,500.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,500.000000,NaN,NaN,NaN,0.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,8.000000,500.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2504.000000,NaN,NaN,NaN,6.000000,3.000000
50%,NaN,NaN,NaN,NaN,NaN,15.000000,800.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5069.000000,NaN,NaN,NaN,27.000000,4.000000
75%,NaN,NaN,NaN,NaN,NaN,27.000000,1000.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7904.000000,NaN,NaN,NaN,57.000000,5.000000
max,NaN,NaN,NaN,NaN,NaN,35.000000,1800.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,376977.000000,NaN,NaN,NaN,120.000000,5.000000

In [43]:
hospital.duplicated().sum()

np.int64(0)